messages:
  - "{player} лёг в кровать и уснул. Спокойной ночи :)"
  - "{player} споткнулся об кровать и уснул. Сладких снов..."
  - "{player} забрался под одеяло от страшных монстров."
  - "{player} решил поспать. Мудро."
  - "{player} дерётся с подушкой. Кажется, подушка победила..."
  - "{player} наелся и спит."
  - "{player} плотно и вкусно покушал и уснул."
  - "У {player} сонный паралич."

# Don't change it
version: @version@