# Percentage of sleeping players needed to skip the night.
# Set 0 so that one player can skip the night.
needSleepers: 50

# The message that will be sent when skipping the night.
# If not necessary, then leave it empty.
messageSkipNight: ""

# The messages that will be sent to everyone when the {player} has gone to bed.
# You can use Minecraft color codes.
messages:
  - "ยง6{player} went to sleep."
  - "ยง6{player} is sleep. Mismatch."
  - "ยง6{player} is sleeping. Good night :)"

# Plugin version. Don't change it.
version: @version@